### ISSUE TITLE
issues moving items at the root level

### ISSUE THREAD

**Issue by cornernote** [ASlatius/yii2-nestable#2]
I am trying to get this working, but have trouble moving items at the root level.  

Do you have a working implementation of this so that I can check it against my code?

When I move a root node to a child, this fires via ajax:
`index.php?r=menu%2Fmenu%2FnodeMove&id=2&par=1&lft=0&rgt=0`

Note the `&lft=0&rgt=0` .. this doesn't seem right.

**Comment by ASlatius** [comment]
PR #5 was integrated.

**Comment by cornernote** [comment]
PR #5 was to move a child node into the root.  This is the opposite, I still cannot move a root node to a child.  Please re-open.

**Comment by ASlatius** [comment]
My bad. I'll reopen the issue. I currently don't have an application for testing & fixing this issue. I'll see what I can do, will probably take some time.

**Comment by ASlatius** [comment]
Could you please try the AllowMoveToRoot branch (https://github.com/Hommer101/yii2-nestable/tree/AllowMoveToRoot)?
Moving to root actually uses `makeRoot()` now. I can't yet get roots moved to a child to attach at the right point (correct `lft`/`rgt` values), will try some more.

**Comment by cornernote** [comment]
how have you been able to use it without the ability to move nodes in and out of the root?

perhaps a quick solution would be to lock 1 item at the root somehow.  Is there a way to do that ?

**Comment by cornernote** [comment]
this patch is not working for me.  If i try to move root level items they tend to vanish after a refresh.

**Comment by ASlatius** [comment]
Could you try and analyze what is going wrong by looking at the DB content? I'm especially interested in what happens to the root/lft/rgt/level columns.

**Comment by cornernote** [comment]
yes, i'll get a dump

**Comment by cornernote** [comment]
create a top level node

``` sql
INSERT INTO `menu` (`name`, `lft`, `rgt`, `depth`) VALUES ('one', 1, 2, 0);
UPDATE `menu` SET `tree`=1 WHERE `id`=1;
```

create another top level node

``` sql
INSERT INTO `menu` (`name`, `lft`, `rgt`, `depth`) VALUES ('two', 1, 2, 0);
UPDATE `menu` SET `tree`=2 WHERE `id`=2;
```

drag two above one

``` sql
UPDATE `menu` SET `lft`=`lft`+2 WHERE (`lft` >= 1) AND (`tree`=2);
UPDATE `menu` SET `rgt`=`rgt`+2 WHERE (`rgt` >= 1) AND (`tree`=2);
UPDATE `menu` SET `depth`=`depth`-1 WHERE ((`lft` >= 3) AND (`rgt` <= 4)) AND (`tree`=2);
UPDATE `menu` SET `lft`=`lft`-2 WHERE ((`lft` >= 3) AND (`lft` <= 4)) AND (`tree`=2);
UPDATE `menu` SET `rgt`=`rgt`-2 WHERE ((`rgt` >= 3) AND (`rgt` <= 4)) AND (`tree`=2);
UPDATE `menu` SET `lft`=`lft`-2 WHERE (`lft` >= 5) AND (`tree`=2);
UPDATE `menu` SET `rgt`=`rgt`-2 WHERE (`rgt` >= 5) AND (`tree`=2);
```

the final data

```
mysql> select * from menu;
+----+------+-----+-----+-------+------+
| id | tree | lft | rgt | depth | name |
+----+------+-----+-----+-------+------+
|  1 |    1 |   1 |   2 |     0 | one  |
|  2 |    2 |   1 |   2 |    -1 | two  |
+----+------+-----+-----+-------+------+
```

**Comment by cornernote** [comment]
create a top level node

```
$model = new Menu;
$model->name = 'one';
$model->makeRoot()
```

create another top level node

```
$model = new Menu;
$model->name = 'two';
$model->makeRoot()
```

drag two above one

```
ajax to:
/index.php?r=menu/menu/nodeMove&id=4&lft=0&rgt=3
```

**Comment by ASlatius** [comment]
Thx for the analysis. I'll take a look at it.

**Comment by friek108** [comment]
Any update on this?

**Comment by ASlatius** [comment]
Fixed by latest pull from @mazurva
